version: "3.9"

services:
  db:
    image: postgres
    volumes:
      - ./data/db:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 3s
      timeout: 30s
      retries: 3
  web:
    build: .
    image: doozez
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      db:
        condition: service_healthy
      migration:
        condition: service_started
  migration:
    image: doozez
    command: python manage.py migrate --noinput
    volumes:
      - .:/code
    depends_on:
      db:
        condition: service_healthy
  test:
    image: doozez
      command: python manage.py test
    volumes:
      - .:/code