# Generated by Django 3.2.4 on 2021-06-17 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('safe', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='invitation',
            old_name='sent_to_user',
            new_name='recipient',
        ),
        migrations.RenameField(
            model_name='invitation',
            old_name='sent_by_user',
            new_name='sender',
        ),
        migrations.AddField(
            model_name='invitation',
            name='status',
            field=models.CharField(choices=[('PND', 'Pending'), ('ACC', 'Accepted'), ('DEC', 'Declined')], default='PND', max_length=3),
        ),
    ]
