# Generated by Django 3.2.4 on 2021-06-22 13:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('safe', '0003_auto_20210621_1135'),
    ]

    operations = [
        migrations.AddField(
            model_name='safe',
            name='initiator',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='initiator', to=settings.AUTH_USER_MODEL),
        ),
    ]
