# Generated by Django 3.2.4 on 2021-06-28 10:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('safe', '0004_safe_initiator'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='invitation',
            unique_together={('sender', 'safe')},
        ),
    ]
