# Generated by Django 3.2.4 on 2021-06-28 20:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('safe', '0005_alter_invitation_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='invitation',
            unique_together={('recipient', 'safe')},
        ),
        migrations.CreateModel(
            name='PaymentMethod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='paymentmethod_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Participation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('PND', 'Pending'), ('ACT', 'Active'), ('CPT', 'Complete'), ('PPT', 'PendingPayment')], default='PND', max_length=3)),
                ('win_sequence', models.PositiveIntegerField()),
                ('invitation', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='invitation', to='safe.invitation')),
                ('payment_method', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payment_method', to='safe.paymentmethod')),
                ('safe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='safe', to='safe.safe')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participation_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
