# Generated by Django 3.2.4 on 2021-06-30 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('safe', '0007_auto_20210629_1023'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActionPayload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('ACCEPT', 'Accept'), ('CANCEL', 'Cancel')], max_length=60)),
            ],
            options={
                'managed': False,
            },
        ),
    ]
