# Generated by Django 3.2.4 on 2021-06-30 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('safe', '0008_actionpayload'),
    ]

    operations = [
        migrations.AddField(
            model_name='participation',
            name='user_role',
            field=models.CharField(choices=[('INT', 'Initiator'), ('PCT', 'Participant')], default='PCT', max_length=3),
        ),
    ]
