# Generated by Django 3.2.4 on 2021-07-05 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('safe', '0009_participation_user_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participation',
            name='status',
            field=models.CharField(choices=[('PND', 'Pending'), ('ACT', 'Active'), ('CPT', 'Complete'), ('PPT', 'PendingPayment'), ('LEF', 'Left')], default='PND', max_length=3),
        ),
    ]
