# Generated by Django 3.2.4 on 2021-07-09 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('safe', '0010_alter_participation_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentmethod',
            name='status',
            field=models.CharField(choices=[('PEA', 'PendingExternalApproval'), ('EAS', 'ExternalApprovalSuccessful'), ('EAF', 'ExternalApprovalFailed')], default='PEA', max_length=3),
        ),
    ]
