# Generated by Django 3.2.4 on 2021-07-09 20:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('safe', '0011_paymentmethod_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='GCFlow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference_id', models.TextField()),
                ('session_token', models.TextField()),
                ('payment_method', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gcflow_payment_method', to='safe.paymentmethod')),
            ],
        ),
    ]
