# Generated by Django 3.2.4 on 2021-07-10 11:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('safe', '0013_rename_reference_id_gcflow_flow_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gcflow',
            name='payment_method',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='safe.paymentmethod'),
        ),
    ]
