# Generated by Django 3.2.4 on 2021-07-10 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('safe', '0014_alter_gcflow_payment_method'),
    ]

    operations = [
        migrations.AddField(
            model_name='gcflow',
            name='flow_redirect_url',
            field=models.TextField(null=True),
        ),
    ]
