# Generated by Django 3.2.4 on 2021-07-10 21:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('safe', '0015_gcflow_flow_redirect_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mandate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.TextField(choices=[('pending_customer_approval', 'pending_customer_approval'), ('pending_submission', 'pending_submission'), ('submitted', 'submitted'), ('active', 'active'), ('failed', 'failed'), ('cancelled', 'cancelled'), ('expired', 'expired'), ('consumed', 'consumed')], default='pending_submission')),
                ('scheme', models.TextField()),
                ('mandate_external_id', models.TextField()),
            ],
        ),
        migrations.AddField(
            model_name='paymentmethod',
            name='mandate',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='safe.mandate'),
        ),
    ]
