# Generated by Django 3.2.4 on 2021-07-11 14:41

from django.db import migrations
import django_fsm


class Migration(migrations.Migration):

    dependencies = [
        ('safe', '0016_auto_20210710_2120'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mandate',
            name='status',
            field=django_fsm.FSMField(choices=[('pending_customer_approval', 'pending_customer_approval'), ('pending_submission', 'pending_submission'), ('submitted', 'submitted'), ('active', 'active'), ('failed', 'failed'), ('cancelled', 'cancelled'), ('expired', 'expired'), ('consumed', 'consumed')], default='pending_submission', max_length=50, protected=True),
        ),
        migrations.AlterField(
            model_name='paymentmethod',
            name='status',
            field=django_fsm.FSMField(choices=[('PEA', 'PendingExternalApproval'), ('EAS', 'ExternalApprovalSuccessful'), ('EAF', 'ExternalApprovalFailed')], default='PEA', max_length=50, protected=True),
        ),
    ]
