# Generated by Django 3.2.4 on 2021-07-13 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('safe', '0017_auto_20210711_1441'),
    ]

    operations = [
        migrations.CreateModel(
            name='DoozezTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('PND', 'Pending'), ('ACT', 'Running'), ('SUC', 'Success'), ('FLD', 'Failed')], default='PND', max_length=3)),
                ('task_type', models.CharField(choices=[('DRW', 'Draw'), ('WFP', 'WithdrawFirstPayment'), ('CRI', 'CreateInstallments'), ('CSS', 'CompleteSafeStart')], max_length=3)),
            ],
        ),
    ]
