# Generated by Django 3.2.4 on 2021-07-19 13:54

from django.db import migrations
import django_fsm


class Migration(migrations.Migration):

    dependencies = [
        ('safe', '0020_doozeztask_parameters'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doozeztask',
            name='status',
            field=django_fsm.FSMField(choices=[('PND', 'Pending'), ('ACT', 'Running'), ('SUC', 'Success'), ('FLD', 'Failed')], default='PND', max_length=50, protected=True),
        ),
    ]
