# Generated by Django 3.2.4 on 2021-07-20 13:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_fsm
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('safe', '0021_alter_doozeztask_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='doozeztask',
            name='exceptions',
            field=jsonfield.fields.JSONField(null=True),
        ),
        migrations.AddField(
            model_name='doozeztask',
            name='sequence',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='doozeztask',
            name='status',
            field=django_fsm.FSMField(choices=[('PND', 'Pending'), ('RUN', 'Running'), ('SUC', 'Success'), ('FLD', 'Failed')], default='PND', max_length=50, protected=True),
        ),
        migrations.CreateModel(
            name='DoozezJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', django_fsm.FSMField(choices=[('CRT', 'Created'), ('SUC', 'Success'), ('FLD', 'Failed')], default='CRT', max_length=50, protected=True)),
                ('job_type', models.CharField(choices=[('SSF', 'StartSafe')], max_length=3)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='doozezjob_user', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='doozeztask',
            name='job',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='doozeztask_job', to='safe.doozezjob'),
        ),
    ]
