# Generated by Django 3.2.4 on 2021-07-22 14:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('safe', '0023_alter_doozeztask_job'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participation',
            name='safe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participations_safe', to='safe.safe'),
        ),
    ]
