# Generated by Django 3.2.4 on 2021-07-22 14:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('safe', '0024_alter_participation_safe'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invitation',
            name='safe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invitations_safe', to='safe.safe'),
        ),
    ]
