# Generated by Django 3.2.4 on 2021-07-25 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('safe', '0025_alter_invitation_safe'),
    ]

    operations = [
        migrations.AddField(
            model_name='doozezuser',
            name='is_system',
            field=models.BooleanField(default=False),
        ),
    ]
