# Generated by Django 3.2.4 on 2021-08-02 18:42

from django.db import migrations, models
import django_fsm


class Migration(migrations.Migration):

    dependencies = [
        ('safe', '0028_add_payment_method_for_system_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invitation',
            name='status',
            field=models.CharField(choices=[('PND', 'Pending'), ('ACC', 'Accepted'), ('DEC', 'Declined'), ('RBS', 'RemovedBySender')], default='PND', max_length=3),
        ),
        migrations.AlterField(
            model_name='participation',
            name='status',
            field=django_fsm.FSMField(choices=[('PND', 'Pending'), ('ACT', 'Active'), ('CPT', 'Complete'), ('PPT', 'PendingPayment'), ('LEF', 'Left')], default='PND', max_length=50, protected=True),
        ),
        migrations.AlterField(
            model_name='participation',
            name='user_role',
            field=models.CharField(choices=[('INT', 'Initiator'), ('PCT', 'Participant'), ('SYS', 'System')], default='PCT', max_length=3),
        ),
    ]
