# Generated by Django 3.2.4 on 2021-08-03 15:20

from django.db import migrations
import django_fsm


class Migration(migrations.Migration):

    dependencies = [
        ('safe', '0029_auto_20210802_1842'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invitation',
            name='status',
            field=django_fsm.FSMField(choices=[('PND', 'Pending'), ('ACC', 'Accepted'), ('DEC', 'Declined'), ('RBS', 'RemovedBySender')], default='PND', max_length=50, protected=True),
        ),
    ]
