# Generated by Django 3.2.4 on 2021-08-11 06:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('safe', '0031_profile'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='invitation',
            unique_together=set(),
        ),
    ]
