# Generated by Django 3.2.4 on 2021-08-11 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('safe', '0032_alter_invitation_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentmethod',
            name='name',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
