# Generated by Django 3.2.4 on 2021-08-13 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('safe', '0034_alter_safe_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='safe',
            name='status',
            field=models.CharField(choices=[('PPT', 'PendingParticipants'), ('STG', 'Starting'), ('STD', 'Started'), ('PDR', 'PendingDraw'), ('PEP', 'PendingEntryPayment'), ('ACT', 'Active'), ('CPT', 'Complete')], default='PPT', max_length=3),
        ),
    ]
