# Generated by Django 3.2.4 on 2021-08-30 17:32

from django.db import migrations
import django_fsm


class Migration(migrations.Migration):

    dependencies = [
        ('safe', '0036_payment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='status',
            field=django_fsm.FSMField(choices=[('pending_submission', 'PendingSubmission'), ('submitted', 'Submitted'), ('confirmed', 'Confirmed'), ('failed', 'Failed'), ('cancelled', 'Cancelled'), ('customer_approval_denied', 'CustomerApprovalDenied'), ('charged_back', 'ChargedBack')], default='pending_submission', max_length=50, protected=True),
        ),
    ]
