# Generated by Django 3.2.4 on 2021-09-01 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('safe', '0038_alter_payment_charge_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doozeztask',
            name='task_type',
            field=models.CharField(choices=[('DRW', 'Draw'), ('CTP', 'CreatePayment'), ('CRI', 'CreateInstallments'), ('CSS', 'CompleteSafeStart')], max_length=3),
        ),
    ]
