# Generated by Django 3.2.4 on 2021-10-01 11:11

from django.db import migrations
import django_fsm


class Migration(migrations.Migration):

    dependencies = [
        ('safe', '0041_alter_site_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doozezjob',
            name='status',
            field=django_fsm.FSMField(choices=[('CRT', 'Created'), ('RNG', 'Running'), ('SUC', 'Success'), ('FLD', 'Failed')], default='CRT', max_length=50, protected=True),
        ),
    ]
