# Generated by Django 3.2.4 on 2021-10-12 11:24

from django.db import migrations, models
import django_fsm
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('safe', '0042_alter_doozezjob_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='GCEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('event_id', models.TextField()),
                ('resource_type', models.TextField()),
                ('action', models.TextField()),
                ('links', jsonfield.fields.JSONField(blank=True, null=True)),
                ('details', jsonfield.fields.JSONField(blank=True, null=True)),
                ('gc_created_at', models.TextField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AlterField(
            model_name='paymentmethod',
            name='status',
            field=django_fsm.FSMField(choices=[('PEA', 'PendingExternalApproval'), ('EAS', 'ExternalApprovalSuccessful'), ('EAF', 'ExternalApprovalFailed'), ('EXS', 'ExternallySubmitted'), ('EXA', 'ExternallySubmitted')], default='PEA', max_length=50, protected=True),
        ),
    ]
