# Generated by Django 3.2.4 on 2021-10-12 14:22

from django.db import migrations, models
import django.db.models.deletion
import django_fsm


class Migration(migrations.Migration):

    dependencies = [
        ('safe', '0044_auto_20211012_1235'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gcevent',
            name='created_on',
        ),
        migrations.RemoveField(
            model_name='gcevent',
            name='updated_at',
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', django_fsm.FSMField(choices=[('CRT', 'Created'), ('RNG', 'Running'), ('SUC', 'Success'), ('FLD', 'Failed')], default='CRT', max_length=50, protected=True)),
                ('gc_event', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='event_user', to='safe.gcevent')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
