# Generated by Django 3.2.4 on 2021-11-03 16:30

from django.db import migrations, models
import django.db.models.deletion
import django_fsm


class Migration(migrations.Migration):

    dependencies = [
        ('safe', '0047_alter_paymentmethod_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentmethod',
            name='mandate',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_query_name='payment_method', to='safe.mandate'),
        ),
        migrations.AlterField(
            model_name='paymentmethod',
            name='status',
            field=django_fsm.FSMField(choices=[('PEA', 'PendingExternalApproval'), ('EAS', 'ExternalApprovalSuccessful'), ('EAF', 'ExternalApprovalFailed'), ('EXC', 'ExternallyCreated'), ('EXS', 'ExternallySubmitted'), ('EXA', 'ExternallyActivated')], default='PEA', max_length=50, protected=True),
        ),
    ]
