# Generated by Django 3.2.4 on 2021-11-09 17:15

from django.db import migrations
import django_fsm


class Migration(migrations.Migration):

    dependencies = [
        ('safe', '0048_auto_20211103_1630'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mandate',
            name='status',
            field=django_fsm.FSMField(choices=[('pending_customer_approval', 'pending_customer_approval'), ('created', 'Created'), ('submitted', 'submitted'), ('active', 'active'), ('failed', 'failed'), ('cancelled', 'cancelled'), ('expired', 'expired'), ('consumed', 'consumed')], default='created', max_length=50, protected=True),
        ),
    ]
