# Generated by Django 3.2.4 on 2021-11-19 15:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('safe', '0051_auto_20211119_1518'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='instalment',
            name='payment_method',
        ),
        migrations.RemoveField(
            model_name='instalment',
            name='safe',
        ),
        migrations.AddField(
            model_name='instalment',
            name='participation',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='installment', to='safe.participation'),
        ),
    ]
