# Generated by Django 3.2.4 on 2022-09-30 12:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('safe', '0054_auto_20220930_1210'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='monthly_payment',
            new_name='price',
        ),
    ]
